nome = str(input('Digite um nome completo:'))
nomeMais = nome.upper()
nomeMenos = nome.lower()
espacos = (nome.count(' '))
primeiro = (nome.find(' '))
print(f'Seu nome em Maiúsculas é {nomeMais}')
print(f'Seu nome em Minúsculas é {nomeMenos}')
print(f'Seu nome tem ao todo {len(nome.strip())-espacos}')
#print(f'Seu primeiro nome tem {primeiro}')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')
